version: '3'

services:
  
  database:
    image: postgres:9.6
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb  # You should choose a better name for your database. 
                          # Do not forget to change the url propertie in the app SPRING_DATASOURCE_URL environment
  pgadmin:
    image: thajeztah/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - /home/$USER/pgadmin4:/pgadmin
    depends_on:
      - database

  app:
    image: ${artifact}
    container_name: webapp
    ports:
      - "8080:8080"
    depends_on:
      - database
      - pgadmin
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  test:
    image: ${artifact}-test
    container_name: webapptest
    build:
      context: .
      dockerfile: Dockerfile.test
    command: sh docker/test.sh

volumes: 
  pgdata:

  pgadmin:
    image: thajeztah/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - /home/$USER/pgadmin4:/pgadmin
    depends_on:
      - database

  app:
    image: appname-docker
    container_name: webapp
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: appname-docker
    command: sh docker/test.sh

volumes: 
  pgdata: