spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: $artifact

flyway:
  schemas: $artifact

endpoints:
  beans:
    sensitive: false

management:
  security:
    enabled: false

server:
  proxy-peer-address: true