version: '3'

services:
  
  database:
    image: postgres:9.6
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb  # You should choose a better name for your database. 
                          # Do not forget to change the url propertie in the app SPRING_DATASOURCE_URL environment
  pgadmin:
    image: thajeztah/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - /home/\$USER/pgadmin4:/pgadmin
    depends_on:
      - database

  app:
    image: ${artifact}
    container_name: webapp
    ports:
      - "8080:8080"
    depends_on:
      - database
      - pgadmin
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_H2_CONSOLE_ENABLED=false

  test:
    image: gradle:4.5.1-jdk8-alpine
    container_name: gradletest
    volumes:
      - \$HOME/.gradle:/home/gradle/.gradle
      - .:/home/gradle
    command: gradle test -Pjenv=test --stacktrace

volumes: 
  pgdata: